name: opsd-timeseries-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.24.0
  - matplotlib>=3.6.0
  - seaborn>=0.12.0
  - scipy>=1.10.0
  - requests>=2.28.0
  - jupyter>=1.0.0
  - ipykernel>=6.16.0
  - pytz>=2022.7
  - holidays>=0.18
  - openpyxl>=3.0.0
  - xlrd>=2.0.0
  - pip
  - pip:
    - pandas-datareader>=0.10.0 